#Copyright 2017 FairwindsOps Inc.
#
#Licensed under the Apache License, Version 2.0 (the “License”);
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an “AS IS” BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@11

references:
  e2e_configuration: &e2e_configuration
    pre_script: end_to_end_testing/pre.sh
    script: end_to_end_testing/run.sh
    command_runner_image: quay.io/reactiveops/ci-images:v11-buster
    enable_docker_layer_caching: true
    store-test-results: /tmp/test-results
    kind_version: 0.10.0
    requires:
      - test
    filters:
      branches:
        only: /.*/
      tags:
        ignore: /.*/
jobs:
  test:
    working_directory: /go/src/github.com/fairwindsops/reckoner
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: package and upload
          command: |
            sudo pip install twine
            python setup.py sdist bdist_wheel
            twine upload dist/*
  publish_docs:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run:
          name: Build Docs Site
          command: |
            set -e
            cd ./docs
            npm install
            npm run check-links
            npm run build
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Publish Docs Site to S3
          command: |
            cd ./dist
            aws s3 sync ./ s3://reckoner.docs.fairwinds.com --delete


workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
      - rok8s/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.18"
          kind_node_image: "kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4"
          <<: *e2e_configuration
      - rok8s/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.19"
          kind_node_image: "kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca"
          <<: *e2e_configuration
      - rok8s/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.20"
          kind_node_image: "kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab"
          <<: *e2e_configuration
      - rok8s/docker_build_and_push:
          name: build-and-push-container
          docker-push: true
          enable_docker_layer_caching: true
          config_file: .circleci/build.config
          context: org-global
          docker-login: true
          password-variable: "fairwinds_quay_token"
          registry: quay.io
          username: fairwinds+circleci
          requires:
            - build-3-7
            - build-3-8
            - "End-To-End Kubernetes 1.18.8"
            - "End-To-End Kubernetes 1.19.1"
          filters:
            branches:
              ignore: /pull\/[0-9]+/
            tags:
              ignore: /.*/
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - rok8s/docker_build_and_push:
          name: build-and-push-container
          docker-push: true
          enable_docker_layer_caching: false
          config_file: .circleci/build.config
          context: org-global
          docker-login: true
          password-variable: "fairwinds_quay_token"
          registry: quay.io
          username: fairwinds+circleci
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - publish_docs:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
